#!/bin/bash
#==============================================================================
# 10.x IP-Adresse ändern (RHEL/Oracle Linux)
#==============================================================================
# Beschreibung: Ändert die 10.x IP-Adresse auf einem RHEL/Oracle Linux System
# Autor: System Administration
# Datum: 2026-03-18
#
# Verwendung:
#   ./change-10x-ip.sh <neue-ip>
#   Beispiel: ./change-10x-ip.sh 10.10.64.150
#==============================================================================

set -euo pipefail

# Farben für Ausgabe
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging-Funktion
log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

error() {
    echo -e "${RED}[FEHLER]${NC} $1" >&2
}

warning() {
    echo -e "${YELLOW}[WARNUNG]${NC} $1"
}

success() {
    echo -e "${GREEN}[ERFOLG]${NC} $1"
}

#==============================================================================
# PARAMETER PRÜFEN
#==============================================================================

if [ $# -ne 1 ]; then
    error "Falsche Anzahl Parameter!"
    echo ""
    echo "Verwendung: $0 <neue-10x-ip>"
    echo "Beispiel:   $0 10.10.64.150"
    exit 1
fi

NEW_IP="$1"

# Prüfe ob IP-Format korrekt ist
if ! [[ "$NEW_IP" =~ ^10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    error "Ungültiges IP-Format: $NEW_IP"
    echo "IP muss mit 10. beginnen und im Format 10.x.x.x sein"
    exit 1
fi

# Prüfe Root-Rechte
if [ "$EUID" -ne 0 ]; then
    error "Dieses Script muss als root ausgeführt werden!"
    echo "Bitte verwenden Sie: sudo $0 $NEW_IP"
    exit 1
fi

#==============================================================================
# SYSTEM-INFORMATIONEN
#==============================================================================

log "Starte 10.x IP-Änderung..."
echo ""
log "System-Informationen:"
echo "  Hostname: $(hostname -f)"
echo "  OS: $(cat /etc/redhat-release 2>/dev/null || echo 'Unbekannt')"
echo "  Neue 10.x IP: $NEW_IP"
echo ""

#==============================================================================
# AKTUELLES 10.x INTERFACE FINDEN
#==============================================================================

log "Suche aktuelles 10.x Interface..."

# Finde Interface mit 10.x IP
CURRENT_10X_INTERFACE=""
CURRENT_10X_IP=""

while IFS= read -r line; do
    IFACE=$(echo "$line" | awk '{print $2}')
    IP=$(echo "$line" | awk '{print $4}' | cut -d'/' -f1)
    
    if [[ "$IP" =~ ^10\. ]]; then
        CURRENT_10X_INTERFACE="$IFACE"
        CURRENT_10X_IP="$IP"
        break
    fi
done < <(ip -o addr show | grep -E 'inet ' | grep -v '127.0.0.1')

if [ -z "$CURRENT_10X_INTERFACE" ]; then
    warning "Kein Interface mit 10.x IP gefunden!"
    
    # Suche nach Interface OHNE IP (für neue 10.x IP)
    log "Suche nach ungenutztem Interface..."
    
    for iface in $(ls /sys/class/net/ | grep -E '^(eth|ens|enp)'); do
        if ! ip addr show "$iface" | grep -q 'inet '; then
            CURRENT_10X_INTERFACE="$iface"
            CURRENT_10X_IP="nicht konfiguriert"
            warning "Verwende ungenutztes Interface: $iface"
            break
        fi
    done
    
    if [ -z "$CURRENT_10X_INTERFACE" ]; then
        error "Konnte kein geeignetes Interface finden!"
        exit 1
    fi
else
    success "10.x Interface gefunden: $CURRENT_10X_INTERFACE ($CURRENT_10X_IP)"
fi

echo ""

#==============================================================================
# BACKUP ERSTELLEN
#==============================================================================

BACKUP_DIR="/root/10x-ip-backup-$(date +%s)"
log "Erstelle Backup in: $BACKUP_DIR"

mkdir -p "$BACKUP_DIR"

# Backup der ifcfg-Datei
IFCFG_FILE="/etc/sysconfig/network-scripts/ifcfg-${CURRENT_10X_INTERFACE}"

if [ -f "$IFCFG_FILE" ]; then
    cp -a "$IFCFG_FILE" "$BACKUP_DIR/"
    success "Backup erstellt: $IFCFG_FILE"
else
    warning "ifcfg-Datei existiert nicht: $IFCFG_FILE (wird neu erstellt)"
fi

# Backup der aktuellen IP-Konfiguration
ip addr show > "$BACKUP_DIR/ip-addr-before.txt"
ip route show > "$BACKUP_DIR/ip-route-before.txt"

echo ""

#==============================================================================
# IFCFG-DATEI ERSTELLEN/AKTUALISIEREN
#==============================================================================

log "Erstelle/Aktualisiere ifcfg-Datei..."

cat > "$IFCFG_FILE" <<EOF
# Network Interface Configuration
# Generated by change-10x-ip.sh on $(date +'%Y-%m-%d %H:%M:%S')
# Device: ${CURRENT_10X_INTERFACE}

TYPE=Ethernet
BOOTPROTO=none
DEFROUTE=no
NAME=${CURRENT_10X_INTERFACE}
DEVICE=${CURRENT_10X_INTERFACE}
ONBOOT=yes
IPADDR=${NEW_IP}
NETMASK=255.255.255.0
DNS1=8.8.8.8
DNS2=8.8.4.4
EOF

success "ifcfg-Datei erstellt: $IFCFG_FILE"
echo ""

log "Inhalt der neuen ifcfg-Datei:"
cat "$IFCFG_FILE" | sed 's/^/  /'
echo ""

#==============================================================================
# NETZWERK-ÄNDERUNGEN ANWENDEN
#==============================================================================

log "Wende Netzwerk-Änderungen an..."

# Prüfe ob NetworkManager läuft
if systemctl is-active --quiet NetworkManager; then
    log "Verwende NetworkManager..."
    
    # Versuche device reapply (ohne Verbindungsunterbrechung)
    if nmcli device reapply "$CURRENT_10X_INTERFACE" 2>/dev/null; then
        success "Netzwerk-Änderungen angewendet (device reapply)"
    else
        warning "device reapply fehlgeschlagen, versuche connection up..."
        
        if nmcli connection up "$CURRENT_10X_INTERFACE" 2>/dev/null; then
            success "Netzwerk-Änderungen angewendet (connection up)"
        else
            warning "NetworkManager-Befehle fehlgeschlagen"
            log "Versuche manuellen Neustart..."
            
            ifdown "$CURRENT_10X_INTERFACE" 2>/dev/null || true
            sleep 2
            ifup "$CURRENT_10X_INTERFACE" 2>/dev/null || true
        fi
    fi
else
    warning "NetworkManager läuft nicht, verwende ifdown/ifup..."
    
    ifdown "$CURRENT_10X_INTERFACE" 2>/dev/null || true
    sleep 2
    ifup "$CURRENT_10X_INTERFACE" 2>/dev/null || true
fi

# Kurze Pause für Netzwerk-Stabilisierung
sleep 3

echo ""

#==============================================================================
# VALIDIERUNG
#==============================================================================

log "Validiere neue Konfiguration..."

# Sammle neue IP-Konfiguration
ip addr show > "$BACKUP_DIR/ip-addr-after.txt"
ip route show > "$BACKUP_DIR/ip-route-after.txt"

# Prüfe ob neue IP konfiguriert ist
if ip addr show "$CURRENT_10X_INTERFACE" | grep -q "$NEW_IP"; then
    success "Neue 10.x IP erfolgreich konfiguriert!"
    echo ""
    log "Aktuelle Konfiguration von $CURRENT_10X_INTERFACE:"
    ip addr show "$CURRENT_10X_INTERFACE" | grep -E "inet " | sed 's/^/  /'
else
    error "Neue IP wurde NICHT konfiguriert!"
    echo ""
    log "Aktuelle Konfiguration von $CURRENT_10X_INTERFACE:"
    ip addr show "$CURRENT_10X_INTERFACE" | grep -E "inet " | sed 's/^/  /'
    echo ""
    warning "Möglicherweise ist ein Neustart erforderlich"
fi

echo ""

#==============================================================================
# ROLLBACK-SCRIPT ERSTELLEN
#==============================================================================

log "Erstelle Rollback-Script..."

cat > "$BACKUP_DIR/rollback.sh" <<'ROLLBACK_EOF'
#!/bin/bash
# Rollback-Script für 10.x IP-Änderung

set -e

BACKUP_DIR="$(dirname "$0")"
IFCFG_FILE="$BACKUP_DIR/ifcfg-*"

echo "Starte Rollback..."

# Stelle alte ifcfg-Datei wieder her
if [ -f $IFCFG_FILE ]; then
    cp -a $IFCFG_FILE /etc/sysconfig/network-scripts/
    echo "ifcfg-Datei wiederhergestellt"
else
    echo "WARNUNG: Keine Backup-ifcfg-Datei gefunden!"
fi

# Netzwerk neu starten
if systemctl is-active --quiet NetworkManager; then
    systemctl restart NetworkManager
    echo "NetworkManager neu gestartet"
else
    echo "WARNUNG: NetworkManager läuft nicht!"
fi

echo "Rollback abgeschlossen!"
echo "Bitte System neu starten: reboot"
ROLLBACK_EOF

chmod +x "$BACKUP_DIR/rollback.sh"
success "Rollback-Script erstellt: $BACKUP_DIR/rollback.sh"

echo ""

#==============================================================================
# ZUSAMMENFASSUNG
#==============================================================================

echo "================================================================================"
success "10.x IP-Änderung abgeschlossen!"
echo "================================================================================"
echo ""
echo "Zusammenfassung:"
echo "  Interface: $CURRENT_10X_INTERFACE"
echo "  Alte IP: $CURRENT_10X_IP"
echo "  Neue IP: $NEW_IP"
echo ""
echo "Backup:"
echo "  Verzeichnis: $BACKUP_DIR"
echo "  Rollback: $BACKUP_DIR/rollback.sh"
echo ""
echo "Nächste Schritte:"
echo "  1. Prüfe IP-Konfiguration: ip addr show $CURRENT_10X_INTERFACE"
echo "  2. Teste Netzwerk-Konnektivität: ping -c 3 10.10.64.1"
echo "  3. Bei Problemen Rollback: bash $BACKUP_DIR/rollback.sh"
echo "  4. System neu starten (empfohlen): reboot"
echo ""
echo "================================================================================"

# Made with Bob
